[tool.poetry]
name = "bugbot"
version = "0.1.0"
description = "A QQ Bot"
authors = ["HanTools233 <hantools@foxmail.com>"]
license = "AGPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
graia-ariadne = {extras = ["standard"], version = "^0.10.2"}
pyyaml = "^6.0"
requests-cache = "^0.9.7"
redis = "^4.4.0"
pymysql = "^1.0.2"
cryptography = "^38.0.4"
requests = "^2.28.1"
aiohttp = {extras = ["speedups"], version = "^3.8.3"}
openai = "^0.25.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
